package(default_visibility = ["//visibility:public"])

cc_library(
    name = "print_message",
    srcs = [
        "print_message.cc",
    ],
    hdrs = [
        "print_message.h",
    ],
    deps = [
        "@fusion_engine_client",
    ],
)
