package(default_visibility = ["//visibility:public"])

cc_binary(
    name = "message_decode",
    srcs = [
        "message_decode.cc",
    ],
    deps = [
        "@p1_fusion_engine_client//cpp",
    ],
)
