package(default_visibility = ["//visibility:public"])

# All example applications.
filegroup(
    name = "examples",
    srcs = [
        "//generate_data",
        "//message_decode",
        "//tcp_client",
        "//udp_client",
    ]
)
