package(default_visibility = ["//visibility:public"])

# All example applications.
filegroup(
    name = "examples",
    srcs = [
        "//convert_time",
        "//generate_data",
        "//lband_decode",
        "//message_decode",
        "//raw_message_decode",
        "//request_version",
        "//tcp_client",
        "//udp_client",
    ],
)
