package(default_visibility = ["//visibility:public"])

cc_binary(
    name = "convert_time",
    srcs = [
        "convert_time.cc",
    ],
    deps = [
        "//common:time_provider",
        "@fusion_engine_client",
    ],
)
