package(default_visibility = ["//visibility:public"])

cc_binary(
    name = "request_version",
    srcs = [
        "request_version.cc",
    ],
    deps = [
        "//common:print_message",
        "@fusion_engine_client",
    ],
)
